### ISSUE TITLE
Modify current idioms

### ISSUE THREAD

**Issue by tarensanders** [tarensanders/screen_viz#1]
# Task One

- [x] Convert to heatmap. Outcome on the y axis, exposure on the x axis
- [x] Try with the subcategories as well
- [x] Try with both effect size and effect count as value

# Task Two

- [x] Change to line for each of the subcategories
- [x] Order by value, not name
- [x] Use the size of the circle to indicate sample size or other forms of uncertainty
- [x] For other uncertainty, use another heatmap on the side, or use a 'score' indicated on the background of the label
- [x] Try using another heatmap instead of line plot

# Task 5

- [ ] Try a spider/radar plot
